minimum_pre_commit_version: 2.15.0

repos:
-   repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        name: flake8 (py)
        types: [python]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    -   id: pyupgrade
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3  
  hooks:
    - id: yamllint
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.1.1
  hooks:
  - id: check-script-semicolon
  - id: check-script-has-no-table-name
  - id: dbt-test
  - id: dbt-docs-generate
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.2.0
  hooks:
    - id: sqlfluff-lint
      name: sqlfluff lint
      entry: sqlfluff lint
      language: python
      types: [sql]
      additional_dependencies:
        - sqlfluff-templater-dbt
        - dbt-bigquery==1.8.2
      args: ["--dialect", "bigquery"]
    - id: sqlfluff-fix
      name: sqlfluff fix
      entry: sqlfluff fix
      language: python
      types: [sql]
      additional_dependencies:
        - sqlfluff-templater-dbt
        - dbt-bigquery==1.8.2
      args: ["--dialect", "bigquery"]
