steps:
  - name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', '${us-central1}-docker.pkg.dev/${mainnet-bigq}/${elt-python}/${connext-lifi}', '.']
images:
  - '${us-central1}-docker.pkg.dev/${mainnet-bigq}/${elt-python}/${connext-lifi}'