steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs', '-f', 'Docker/Dockerfile.jobs', '.']
images:
- 'us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs'
