steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs",
        "-f",
        "Docker/Dockerfile.routes-jobs",
        "."
      ]
      
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-defilamma",
        "-f",
        "Docker/Dockerfile.defilamma-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-all-bridge-explorer-jobs",
        "-f",
        "Docker/Dockerfile.all-bridge-explorer-jobs",
        "."
      ]
images:
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-defilamma"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-all-bridge-explorer-jobs"

