connext_dbt:
  outputs:
    dev:
      dataset: public
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: creds/mainnet-bigq-b32efe721225.json
      location: US
      method: service-account
      priority: interactive
      project: mainnet-bigq
      threads: 10
      type: bigquery
  target: dev