name: 'connext_dbt'
version: '1.8.0'
config-version: 2
profile: 'connext_dbt'
model-paths: ["models", "docs"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
seeds:
  connext_dbt:
    list_of_tokens_symbols:
      +schema: metadata
    chains:
      +schema: metadata
models:
  connext_dbt:
    dune:
      +materialized: view
      +schema: dune
    bridges:
      +materialized: view
      +schema: bridges
    dbt_profiler:
      +materialized: view
      +schema: profiles
    everclear:
      +materialized: view
      +schema: everclear