name: 'connext_dbt'
version: '1.0.0'
config-version: 2
profile: 'connext_dbt'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
seeds:
  connext_dbt:
    list_of_tokens_symbols:
      +column_types:
        token_symbol: varchar(10)
models:
  connext_dbt:
    metrics:
      +materialized: view
      +schema: metrics
    stage:
      +materialized: view
      +schema: stage
    raw:
      +materialized: view
      +schema: raw
    dune:
      +materialized: view
      +schema: dune
    legacy:
      +materialized: view
      +schema: legacy
    metrics_routers_lp_pools:
      +materialized: view
      +schema: metrics_routers_lp_pools
    crypto_bridges_aggregate:
      +materialized: view
      +schema: crypto_bridges_aggregate
    ad_hoc:
      +materialized: view
      +schema: ad_hoc
    bridges:
      +materialized: view
      +schema: bridges