-- Top 100 rows from each table

-- assets:
    -- Takeaway: 
    -- 1. there are 2 assets with addresses
SELECT 'assets' AS table_name, * FROM public.assets LIMIT 100

-- Balances: Nothing in balance
SELECT 'balances' AS table_name, * FROM public.balances LIMIT 100

-- checkpoints: There are check_names: origin/hub_invoice___chain_ids and other cols is check_point: not sure what that is
SELECT 'checkpoints' AS table_name, * FROM public.checkpoints LIMIT 100

-- no data on depositors
SELECT 'depositors' AS table_name, * FROM public.depositors LIMIT 100

-- no data on destination_intents
SELECT 'destination_intents' AS table_name, * FROM public.destination_intents LIMIT 100

-- data by id -> domain | message_id | etc 
SELECT 'hub_intents' AS table_name, * FROM public.hub_intents LIMIT 100

SELECT 'messages' AS table_name, * FROM public.messages LIMIT 100

-- origin_intents, queues, tokens
SELECT 'origin_intents' AS table_name, * FROM public.origin_intents LIMIT 100


-- materialized view: intents
SELECT 'intents' AS table_name, * FROM public.intents LIMIT 100

-- Queue to be used for calculate invoice remains
SELECT 'queues' AS table_name, * FROM public.queues LIMIT 100
--
SELECT 'tokens' AS table_name, * FROM public.tokens LIMIT 100;

-- invoices
SELECT 'invoices' AS table_name, * FROM public.invoices LIMIT 100

-- query views: Intent
SELECT 'public.hub_invoices' AS table_name, * FROM public.hub_invoices LIMIT 100


-- check for user access to Public reader
SELECT schemaname, tablename
FROM pg_tables
WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
AND NOT EXISTS (
    SELECT 1
    FROM information_schema.role_table_grants
    WHERE table_schema = schemaname
    AND table_name = tablename
    AND grantee = CURRENT_USER
    AND privilege_type = 'SELECT'
);



-- token Epoch timestamp : changes to token epoch bps every week take a note of cahges as log


-- Metric SQLs:

-- Metric 1: Settlement_Rate_3h
-- ISSUE: Confirm for change is type IS NOT RECORDED as LOG. DATA IS ALTERED for state changes.
SELECT
    DATE_TRUNC('hour', to_timestamp(m.timestamp)) as hour,
    COUNT(m.id) as total_intent_count,
    COUNT(CASE WHEN m.type = 'SETTLEMENT' THEN 1 END) as settled_count,
    COUNT(CASE WHEN m.type = 'SETTLEMENT' THEN 1 END) / COUNT(m.id) as prct_of_settled_count
FROM public.messages m
GROUP BY 1


-- Metric 2: Invoices_1h_Retention_Rate- Percentage of invoices that remain in the system for ~1h
-- ISSUE: change is type IS NOT RECORDED as LOG. DATA IS ALTERED for state changes.
SELECT
    DATE_TRUNC('hour', to_timestamp(i.origin_timestamp)) as hour,
    COUNT(CASE
        WHEN hub_filled_timestamp - hub_added_timestamp <= 3600 THEN id
    END) AS count_of_invoices_within_1h,
    COUNT(id) AS total_count_of_invoices
FROM public.intents i
GROUP BY 1


-- Metric 3: Epoch_Discounts- Number of epoch discounts applied to the invoice before settlement
-- LOGIC: based on the epoch logic using the above intents table create this metric
-- ISSUE: understand the epoch logic and implement it here


-- Metric 4: volume by market maker- Trading_Volume
-- which amount to use origin_amount or hub_invoice_amount
-- TODO: implement metadata for wallet address recognition
SELECT 
 DATE_TRUNC('day', to_timestamp(i.origin_timestamp)) as day,
 SUM(i.origin_amount) as volume_by_market_maker
 FROM public.invoices i
 GROUP BY 1

-- Metric 5: Discount_value- The daily average discount applied to invoices
-- todo: remove fee from the amount
SELECT 
    DATE_TRUNC('day', to_timestamp(i.origin_timestamp)) as day,
    AVG(i.origin_amount - i.hub_invoice_amount + (i.origin_gas_limit * i.origin_gas_price)) as discount_value
 FROM public.invoices i
 GROUP BY 1

-- Metric 6: 

- **APY**: Annual Percentage Yield for MM

- **KR1_Clearing_Volume**: Clearing volume (settlement + netted)
    -- settlement: sum of all settled amount in hub_intent table
    -- netted: 

- **KR2_Netting_Rate**
  - Category: OKRs
  - Description: Percentage of transactions netted within 24 hours
  - Target: KR2: 60% netted within 24h
  - Property: by chains; by assets
  -- SQL-> hub_intent_table -> settled / dispatched and no hub invoice for the itent id

- **KR3_Total_rebalancing_fee**: Total fee = Protocol fee + Discount

- **Settlement_Rate_6h**: Percentage of transactions settled within 6 hours


- **Settlement_Rate_24h**: Percentage of transactions settled within 24 hours

- **Total_Protocol_Revenue**: Total revenue generated by the protocol
    - origin_intents amount  by each token fee percent

- **Settlement_Time**: Average time taken to settle the intent
    -- 

- **Wallet_retention_rate**: Measures the frequency and consistency of user activity associated with specific wallet addresses over time
    - user 1:
    - user 2:

- **Average_intent_size**- Average check
- **Amount_of_intents**: Number of intents



-- Questions:
-- Time based log for tables where there is status change
-- Discount for epoch calculation- is it the same invoice hub