version: 2

seeds:
  - name: list_of_tokens_symbols
    description: "A seed table containing a list of token symbols to pull."
    columns:
      - name: token_symbol
        description: "The symbol of the token."
        data_type: STRING
      - name: price_symbol
        description: "The symbol of the token that has a price associated with the token symbol."
        data_type: STRING
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - token_symbol
            - price_symbol

  - name: chains
    description: "A seed table containing a list of chain names to pull."
    columns:
      - name: chain_id
        description: "The chain id of the chain."
        data_type: INT64
        data_test:
          - not_null
          - unique
      - name: name
        description: "The name of the chain, short name."
        data_type: STRING
        data_test:
          - not_null
          - unique
      - name: fee_token_symbol
        description: "The symbol of the token used to pay for fees on the chain."
        data_type: STRING
        data_test:
          - not_null
      - name: fee_token_decimal
        description: "The decimal of the token used to pay for fees on the chain."
        data_type: INT64
        data_test:
          - not_null
