steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-router-protocol-jobs",
        "-f",
        "Docker/Dockerfile.router-protocol-jobs",
        "."
      ]
images:
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-router-protocol-jobs"
