steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/streamlit/connext-volume-netting-streamlit",
        "-f",
        "Docker/Dockerfile.streamlit-volume-netting",
        "."
      ]
images:
  - "us-central1-docker.pkg.dev/mainnet-bigq/streamlit/connext-volume-netting-streamlit"
