steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs",
        "-f",
        "Docker/Dockerfile.routes-jobs",
        "."
      ]
      
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-defilamma",
        "-f",
        "Docker/Dockerfile.defilamma-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-all-bridge-explorer-jobs",
        "-f",
        "Docker/Dockerfile.all-bridge-explorer-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-debridge-explorer-jobs",
        "-f",
        "Docker/Dockerfile.debridge-explorer-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-symbiosis-bridge-explorer-jobs",
        "-f",
        "Docker/Dockerfile.symbiosis-bridge-explorer-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-pipeline-service",
        "-f",
        "Docker/Dockerfile.pipeline-service",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-synapseprotocol-explorer-jobs",
        "-f",
        "Docker/Dockerfile.synapseprotocol-explorer-jobs",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/streamlit/connext-modelling-service",
        "-f",
        "Docker/Dockerfile.streamlit-connext-modelling-service",
        "."
      ]
images:
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-pipeline-service"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-lifi-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-defilamma"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-all-bridge-explorer-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-debridge-explorer-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-symbiosis-bridge-explorer-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/connext-synapseprotocol-explorer-jobs"
  - "us-central1-docker.pkg.dev/mainnet-bigq/streamlit/connext-modelling-service"
