steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/synapseprotocol-explorer-jobs",
        "-f",
        "Docker/Dockerfile.synapseprotocol-explorer-jobs",
        "."
      ]
images:
  - "us-central1-docker.pkg.dev/mainnet-bigq/elt-python/synapseprotocol-explorer-jobs"
